# Generated by Django 3.1.3 on 2020-11-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_data',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referal',
        ),
        migrations.DeleteModel(
            name='Personal_data',
        ),
    ]
