# Generated by Django 3.1.3 on 2020-11-30 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('parents_lastname', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=7)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media')),
                ('relation', models.CharField(choices=[('self', 'SELF'), ('mother', 'MOTHER'), ('father', 'FATHER'), ('brother', 'BROTHER'), ('sister', 'SISTER'), ('son', 'SON'), ('daughter', 'DAUGHTER'), ('husband', 'HUSBAND'), ('wife', 'WIFE')], max_length=20)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('referal_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Personal_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
